## PowerDNS Auth Server配置
image:
  repository: powerdns/pdns-auth-49
  tag: latest
  pullPolicy: IfNotPresent

## 初始化Job配置
initJob:
  image:
    repository: bitnami/kubectl
    tag: latest
    pullPolicy: IfNotPresent

## 副本数量
replicaCount: 1

## 资源限制
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

## 安全上下文
securityContext:
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101
  capabilities:
    add:
      - NET_BIND_SERVICE
    drop:
      - ALL

## 数据库配置
database:
  ## 数据库类型: mysql, pgsql, sqlite3
  type: mysql
  
  ## MySQL配置
  mysql:
    host: mysql
    port: 3306
    user: powerdns
    password: powerdns
    database: powerdns
    
  ## PostgreSQL配置
  pgsql:
    host: postgresql
    port: 5432
    user: powerdns
    password: powerdns
    database: powerdns
    
  ## SQLite3配置
  sqlite3:
    database: /var/lib/powerdns/pdns.sqlite3
    
  ## 数据库初始化配置
  init:
    enabled: true
    skipCreate: false
    skipInit: false

## PowerDNS配置
## 所有配置都将转换为PDNS_前缀的环境变量
## 例如：allow-axfr-ips将变为PDNS_ALLOW_AXFR_IPS
config:
  launch: "g${database.type}"
  api: "yes"
  api-key: "changeme"
  webserver: "yes"
  webserver-address: "0.0.0.0"
  webserver-allow-from: "0.0.0.0/0,::/0"
  webserver-port: "8081"
  local-address: "0.0.0.0, ::"
  local-port: "53"
  log-dns-queries: "no"
  loglevel: "3"
  master: "yes"
  default-soa-name: "ns1.example.org"
  default-soa-mail: "hostmaster.example.org"
  allow-axfr-ips: "127.0.0.0/8,::1/128"
  allow-notify-from: "0.0.0.0/0,::/0"
  daemon: "no"
  disable-axfr: "no"
  guardian: "yes"
  default-ttl: "3600"
  receiver-threads: "1"
  distributor-threads: "3"

## 服务配置
service:
  type: ClusterIP
  port: 53
  apiPort: 8081
  annotations: {}
  loadBalancerIP: ""
  externalTrafficPolicy: ""

## 持久卷配置（用于SQLite3）
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

## 健康检查配置
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

## Pod注解
podAnnotations: {}

## 节点选择器
nodeSelector: {}

## 容忍度
tolerations: []

## 亲和性
affinity: {}

## ServiceAccount配置
serviceAccount:
  create: true
  annotations: {}
  name: ""

## Pod安全策略
podSecurityContext: {}

## 网络策略
networkPolicy:
  enabled: false

## 入口配置
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: pdns-api.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: [] 