{{- if .Values.vaultwarden.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.adminTokenSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  admin-token: {{ .Values.vaultwarden.adminToken | b64enc }}
---
{{- end }}

{{- if .Values.vaultwarden.smtp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.smtpSecretName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.vaultwarden.smtp.username | b64enc }}
  password: {{ .Values.vaultwarden.smtp.password | b64enc }}
---
{{- end }}

{{- if .Values.externalDatabase.mysql.enabled }}
{{- if not .Values.externalDatabase.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-mysql
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "mysql://%s:%s@%s:%v/%s" .Values.externalDatabase.mysql.username .Values.externalDatabase.mysql.password .Values.externalDatabase.mysql.host .Values.externalDatabase.mysql.port .Values.externalDatabase.mysql.database | b64enc }}
{{- end }}
---
{{- end }}

{{- if .Values.externalDatabase.postgres.enabled }}
{{- if not .Values.externalDatabase.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}-postgres
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.externalDatabase.postgres.username .Values.externalDatabase.postgres.password .Values.externalDatabase.postgres.host .Values.externalDatabase.postgres.port .Values.externalDatabase.postgres.database | b64enc }}
{{- end }}
{{- end }}