apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.vaultwarden.websocketEnabled .Values.service.websocket.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultwarden.websocketServiceName" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.websocket.port }}
      targetPort: {{ .Values.service.websocket.targetPort }}
      protocol: TCP
      name: websocket
  selector:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
{{- end }}