{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pdns-auth.fullname" . }}
  labels:
    {{- include "pdns-auth.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pdns-auth.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow DNS traffic
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow API traffic
    - ports:
        - port: 8081
          protocol: TCP
  egress:
    # Allow DNS traffic
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    # Allow database connections
    {{- if eq .Values.database.type "mysql" }}
    - to:
        - ipBlock:
            cidr: {{ .Values.database.mysql.host }}/32
      ports:
        - port: {{ .Values.database.mysql.port }}
          protocol: TCP
    {{- else if eq .Values.database.type "pgsql" }}
    - to:
        - ipBlock:
            cidr: {{ .Values.database.pgsql.host }}/32
      ports:
        - port: {{ .Values.database.pgsql.port }}
          protocol: TCP
    {{- end }}
    # Allow HTTP/HTTPS for updates
    - ports:
        - port: 80
          protocol: TCP
        - port: 443
          protocol: TCP
{{- end }} 