{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "pdns-admin.fullname" . }}
  labels:
    {{- include "pdns-admin.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "pdns-admin.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.config.port }}
          protocol: TCP
{{- end }} 