apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdns-admin.fullname" . }}
  labels:
    {{- include "pdns-admin.labels" . | nindent 4 }}
type: Opaque
data:
  # Flask configuration
  secret_key: {{ .Values.config.secret_key | b64enc | quote }}
  salt: {{ .Values.config.salt | b64enc | quote }}
  
  # PowerDNS API configuration
  pdns_api_key: {{ .Values.pdns.api_key | b64enc | quote }}
  
  # Database passwords
  {{- if eq .Values.database.type "mysql" }}
  db_password_mysql: {{ .Values.database.mysql.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.database.type "postgres" }}
  db_password_postgres: {{ .Values.database.postgres.password | b64enc | quote }}
  {{- end }}
  
  # Authentication secrets
  {{- if .Values.auth.ldap.enabled }}
  {{- if .Values.auth.ldap.admin_password }}
  ldap_admin_password: {{ .Values.auth.ldap.admin_password | b64enc | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.auth.oauth.google.enabled }}
  google_oauth_client_secret: {{ .Values.auth.oauth.google.client_secret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.auth.oauth.github.enabled }}
  github_oauth_secret: {{ .Values.auth.oauth.github.secret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.auth.oauth.azure.enabled }}
  azure_oauth_secret: {{ .Values.auth.oauth.azure.secret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.auth.oauth.oidc.enabled }}
  oidc_oauth_secret: {{ .Values.auth.oauth.oidc.secret | b64enc | quote }}
  {{- end }}
  
  # Admin user password
  {{- if .Values.admin.enabled }}
  admin_password: {{ .Values.admin.password | b64enc | quote }}
  {{- end }} 