apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdns-auth.fullname" . }}-pdns-config
  labels:
    {{- include "pdns-auth.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-7"
data:
  pdns.conf: |
    # This file will be populated by the init-job
    # Default configuration - will be replaced during initialization
    api = yes
    api-key = changeme
    webserver = yes
    webserver-address = 0.0.0.0
    webserver-allow-from = 0.0.0.0/0,::/0
    webserver-port = 8081
    local-address = 0.0.0.0, ::
    local-port = 53
    log-dns-queries = no
    loglevel = 3
    master = yes
    default-soa-name = ns1.example.org
    default-soa-mail = hostmaster.example.org
    allow-axfr-ips = 127.0.0.0/8,::1/128
    allow-notify-from = 0.0.0.0/0,::/0
    daemon = no
    disable-axfr = no
    guardian = yes
    default-ttl = 3600
    receiver-threads = 1
    distributor-threads = 3 