apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pdns-auth.fullname" . }}
  labels:
    {{- include "pdns-auth.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
type: Opaque
data:
  {{- if eq .Values.database.type "mysql" }}
  PDNS_gmysql_password: {{ .Values.database.mysql.password | b64enc | quote }}
  {{- else if eq .Values.database.type "pgsql" }}
  PDNS_gpgsql_password: {{ .Values.database.pgsql.password | b64enc | quote }}
  {{- end }}
  {{- if (index .Values.config "api-key") }}
  PDNS_api_key: {{ (index .Values.config "api-key") | b64enc | quote }}
  {{- end }}